import type { Course } from "./types";

export const DEFAULT_FEATURED_COURSES: Course[] = [
  {
    id: "physics",
    title: "الفيزياء للثانوية العامة",
    subjectBadge: "فيزياء",
    subjectVariant: "orange",
    imageSrc: "/courses/course_physics.jpg",
    imageAlt: "كورس الفيزياء للثانوية العامة",
    teacherName: "أ. محمد سعيد",
    studentsCount: "12.5K طالب",
    rating: 4.9,
    href: "/courses/physics-sec3",
  },
  {
    id: "math",
    title: "رياضيات الصف الثالث الإعدادي",
    subjectBadge: "رياضيات",
    subjectVariant: "blue",
    imageSrc: "/courses/course_math.jpg",
    imageAlt: "كورس رياضيات الصف الثالث الإعدادي",
    teacherName: "أ. محمد السيد",
    studentsCount: "9.8K طالب",
    rating: 4.8,
    href: "/courses/math-prep3",
  },
  {
    id: "english",
    title: "اللغة الإنجليزية للثانوية",
    subjectBadge: "لغة إنجليزية",
    subjectVariant: "purple",
    imageSrc: "/courses/course_english.jpg",
    imageAlt: "كورس اللغة الإنجليزية للثانوية العامة",
    teacherName: "Sarah Ahmed",
    studentsCount: "8.2K طالب",
    rating: 4.7,
    href: "/courses/english-secondary",
  },
  {
    id: "chemistry",
    title: "كيمياء الصف الثاني الثانوي",
    subjectBadge: "كيمياء",
    subjectVariant: "red",
    imageSrc: "/courses/course_chemistry.jpg",
    imageAlt: "كورس كيمياء الصف الثاني الثانوي",
    teacherName: "أ. أحمد كامل",
    studentsCount: "7.2K طالب",
    rating: 4.9,
    href: "/courses/chemistry-sec2",
  },
];
