import type { EducationalStage } from "./types";

export const DEFAULT_EDUCATIONAL_STAGES: EducationalStage[] = [
  {
    id: "primary",
    variant: "blue",
    iconName: "backpack",
    imageSrc: "/stages/primary_backpack.jpg",
    imageAlt: "المرحلة الابتدائية - حقيبة مدرسة",
    title: "المرحلة الابتدائية",
    titleColor: "blue",
    subtitle: "(الصف الرابع - السادس)",
    description: "بناء أساس قوي في جميع المواد الأساسية",
    subjectsCount: 6,
    lessonsCount: "+200",
    buttonText: "الصف 4 - 6",
    buttonHref: "#stages-primary",
  },
  {
    id: "prep",
    variant: "green",
    iconName: "book",
    imageSrc: "/stages/prep_book.jpg",
    imageAlt: "المرحلة الإعدادية - كتاب مفتوح",
    title: "المرحلة الإعدادية",
    titleColor: "blue",
    subtitle: "(الأول - الثالث)",
    description: "تعلم أعمق وتنمية المهارات التحليلية",
    subjectsCount: 12,
    lessonsCount: "+350",
    buttonText: "الصف 1 - 3 إعدادي",
    buttonHref: "#stages-prep",
  },
  {
    id: "sec1",
    variant: "orange",
    iconName: "target",
    imageSrc: "/stages/sec1_target.jpg",
    imageAlt: "المرحلة الثانوية - الصف الأول",
    title: "المرحلة الثانوية",
    titleColor: "orange",
    subtitle: "(الصف الأول)",
    description: "تأسيس قوي للمواد العلمية والأدبية",
    subjectsCount: 14,
    lessonsCount: "+400",
    buttonText: "الصف 1 ثانوي",
    buttonHref: "#stages-sec1",
  },
  {
    id: "sec2",
    variant: "blue",
    iconName: "cap",
    imageSrc: "/stages/sec2_cap.jpg",
    imageAlt: "المرحلة الثانوية - الصف الثاني",
    title: "المرحلة الثانوية",
    titleColor: "blue",
    subtitle: "(الصف الثاني)",
    description: "التعمق في المواد واختيار المسار المناسب",
    subjectsCount: 15,
    lessonsCount: "+450",
    buttonText: "الصف 2 ثانوي",
    buttonHref: "#stages-sec2",
  },
  {
    id: "sec3",
    variant: "orange",
    iconName: "trophy",
    imageSrc: "/stages/sec3_trophy.jpg",
    imageAlt: "المرحلة الثانوية - الصف الثالث",
    title: "المرحلة الثانوية",
    titleColor: "orange",
    subtitle: "(الصف الثالث)",
    description: "الاستعداد للامتحانات وتحقيق أعلى الدرجات",
    subjectsCount: 16,
    lessonsCount: "+500",
    buttonText: "الصف 3 ثانوي",
    buttonHref: "#stages-sec3",
  },
];
