import type { EducationalStage } from "./types";

export const DEFAULT_EDUCATIONAL_STAGES: EducationalStage[] = [
  {
    id: "cs_track",
    variant: "orange",
    iconName: "target",
    imageSrc: "/stages/sec1_target.jpg",
    imageAlt: "مسار علوم الحاسب والذكاء الاصطناعي",
    title: "مسار علوم الحاسب",
    titleColor: "orange",
    subtitle: "(جميع المراحل الدراسية)",
    description: "برمجة، ذكاء اصطناعي، أمن سيبراني، وشبكات",
    subjectsCount: 8,
    lessonsCount: "+600",
    buttonText: "علوم الحاسب",
    buttonHref: "/register?stage=cs_track",
  },
  {
    id: "baccalaureate",
    variant: "blue",
    iconName: "trophy",
    imageSrc: "/stages/sec3_trophy.jpg",
    imageAlt: "نظام البكالوريا الجديد",
    title: "نظام البكالوريا الجديد",
    titleColor: "blue",
    subtitle: "(تعليم عام وأزهري)",
    description: "شامل لمناهج البكالوريا الحديثة والمهارات الحياتية",
    subjectsCount: 10,
    lessonsCount: "+450",
    buttonText: "البكالوريا الجديد",
    buttonHref: "/register?system=baccalaureate",
  },
  {
    id: "primary",
    variant: "blue",
    iconName: "backpack",
    imageSrc: "/stages/primary_backpack.jpg",
    imageAlt: "المرحلة الابتدائية - عام وأزهري",
    title: "المرحلة الابتدائية",
    titleColor: "blue",
    subtitle: "(الصف الرابع - السادس)",
    description: "بناء أساس قوي في المواد للعام والأزهر",
    subjectsCount: 6,
    lessonsCount: "+200",
    buttonText: "الصف 4 - 6",
    buttonHref: "/register?stage=primary",
  },
  {
    id: "prep",
    variant: "green",
    iconName: "book",
    imageSrc: "/stages/prep_book.jpg",
    imageAlt: "المرحلة الإعدادية - عام وأزهري",
    title: "المرحلة الإعدادية",
    titleColor: "blue",
    subtitle: "(الأول - الثالث)",
    description: "تعلم أعمق وتنمية المهارات التحليلية الشرعية والعلمية",
    subjectsCount: 12,
    lessonsCount: "+350",
    buttonText: "الصف 1 - 3 إعدادي",
    buttonHref: "/register?stage=prep",
  },
  {
    id: "sec3",
    variant: "orange",
    iconName: "cap",
    imageSrc: "/stages/sec3_trophy.jpg",
    imageAlt: "المرحلة الثانوية - عام وأزهري",
    title: "المرحلة الثانوية",
    titleColor: "orange",
    subtitle: "(الصف الأول - الثالث)",
    description: "تأسيس قوي للامتحانات وتحقيق أعلى الدرجات",
    subjectsCount: 16,
    lessonsCount: "+500",
    buttonText: "الثانوية العامة والأزهرية",
    buttonHref: "/register?stage=secondary3",
  },
];
